<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.props"
          Condition="'$(NuGetBuild)' != 'true' "/>

  <PropertyGroup>
    <Title>Lombiq Privacy for Orchard Core</Title>
    <Copyright>Copyright © 2018, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Privacy for Orchard Core: Orchard module containing features related to data protection/privacy and the EU law on it, the General Data Protection Regulation (GDPR). See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;GDPR;Privacy</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Privacy</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Privacy</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.CustomSettings" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Forms" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Liquid" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Navigation" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Users" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.5.0" />
  </ItemGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true' "/>

</Project>
