name: Lint Scripts and Styles

# Runs for PRs opened for any branch, and pushes to the main branch.
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Scripts and Styles
    uses: Lombiq/NodeJs-Extensions/.github/workflows/lint.yml@issue/OCC-314
    with:
      styles-css: '{ "Lombiq.Privacy": { "styles": { "source": "wwwroot/css" } } }'
